trigger:
  branches:
    include:
      - main

pool:
  name: 'test'   # self-hosted Linux agent pool

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install -y python3.10 python3.10-venv python3.10-dev
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
    sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
    python --version
    python -m ensurepip
  displayName: 'Install Python 3.10'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install pytest
  displayName: 'Install dependencies'

- script: |
    mkdir -p test-results
    pytest --junitxml=test-results/results.xml
    ls -l test-results
    if [ -f test-results/results.xml ]; then
      echo "Test results file found."
    else
      echo "ERROR: Test results file not found!"
      exit 1
    fi
  displayName: 'Run tests and generate test report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'PythonApp'
    publishLocation: 'Container'
  displayName: 'Publish artifact'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'
