trigger:
  branches:
    include:
      - main    # runs pipeline on push to main branch

pool:
  name: 'test'   # self-hosted Linux agent pool

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install -y python3.10 python3.10-venv python3.10-dev
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
    sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
    python --version
    python -m ensurepip
  displayName: 'Install Python 3.10'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install pytest
  displayName: 'Install dependencies'

- script: |
    mkdir -p $(System.DefaultWorkingDirectory)/test-results
    pytest --junitxml=$(System.DefaultWorkingDirectory)/test-results/results.xml
    ls -l $(System.DefaultWorkingDirectory)/test-results
  displayName: 'Run tests and list test results'

- script: |
    echo "Confirming test result XML exists:"
    test -f $(System.DefaultWorkingDirectory)/test-results/results.xml && echo "File exists" || echo "File NOT found"
  displayName: 'Check if test results XML file exists'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results/results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'

  - task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'PythonApp'
    publishLocation: 'Container'
  displayName: 'Publish artifact'


  





